version: '3'

services:
  bind9:
    container_name: viv-dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Asia/Seoul
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - /Users/vivakr/Docker/Dns/config:/etc/bind
      - /Users/vivakr/Docker/Dns/cache:/var/cache/bind
      - /Users/vivakr/Docker/Dns/records:/var/lib/bind
    restart: unless-stopped
