services:
  bind9:
    container_name: viv-bind
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Asia/Seoul
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '10001:10001/tcp'
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped
