FROM ubuntu:latest
RUN apt-get update


#! (Apple M1) docker build -t ubuntu --platform linux/arm64/v8

# docker run -it --name ubuntu ubuntu-vv:latest

# docker run -td --name viv-ubuntu ubuntu-vv:latest

#! docker run -td --privileged --name viv-ubuntu --restart unless-stopped --hostname viv -e 'TZ=Asia/Seoul' -p 59222:22 -p 53:53 -p 53:53/udp viv-ubuntu:latest /sbin/init

# docker-compose -f dockerfile.yml up -d --no-recreate

# docker commit $ContainerID <ImageName>
