services:
  db:
    image: mariadb:latest
    container_name: viv-mariadb
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 58273:3306
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    container_name: viv-wordpress
    volumes:
      - ./html:/var/www/html
    ports:
      - 39715:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
volumes:
  maria_db_data:
  wp_data:

    # http://localhost:39715
