version: "3.1"

services:
  app:
    image: wordpress:latest
    container_name: viv-wordpress
    hostname: wordpress
    volumes:
      - ~/Docker/Wordpress/html:/var/www/html
    ports:
      - "22220:80"
    restart: unless-stopped
    environment:
        WORDPRESS_DB_HOST: 192.168.0.8:59073
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: "<MySQL?DB%Password>" 

# $docker-compose up 
