version: '3.1'

services:
  db:
    image: mysql
    container_name: viv-mysql
    ports:
      - 59073:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 # 한글설정 1
      - --collation-server=utf8mb4_unicode_ci # 한글설정 2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Password!비밀번호"
    volumes:
      # 로컬 볼륨설정
      - /Users/vivabm/Database/MySQL-Data:/var/lib/mysql


## 1. run ##
# $ docker-compose up -d

## 2. connect docker shell ##
# $ docker exec -it viv-mysql

## 2. first connection for configurations mysql  ##
# docker>root@host: $ mysql -u root -p

## 3. mysql crate user for admin ##
# mysql> create user 'viv'@'%' identified by 'password';
# mysql> grant all privileges on *.* to 'viv@'%';
# mysql> flush privileges;
# mysql> quit
