version: '3.1'

services:
  db:
    image: mysql
    container_name: viv-mysql
    ports:
      - 59073:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 # 한글설정 1
      - --collation-server=utf8mb4_unicode_ci # 한글설정 2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "<비밀번호>"
    volumes:
      /Users/vivabm/Docker/MySQL/Data:/var/lib/mysql


## 1. run ##
# $ docker-compose up -d

## 2. connect docker shell ##
# (1) $ docker exec -it viv-mysql mysql -p

## 2. first connection for configurations mysql  ##
# (2) docker>root@host: $ mysql -u root -p

## 3. mysql crate user for admin ##
# (3) mysql> create user 'viv'@'%' identified by 'password';
# (4) mysql> grant all privileges on *.* to 'viv@'%';
# (5) mysql> flush privileges;
# (6) mysql> quit
