version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: viv-postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 59073:5432
    volumes:
      - /Users/vivakr/Docker/Postgres/Data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

