services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: viv-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vivabm
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=ko-KR --data-checksums
    ports:
      - 59293:5432
    volumes:
      - ./data:/var/lib/postgres/data
