version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: viv-postgresql
    environment:
      POSTGRES_USER: vivakr
      POSTGRES_PASSWORD: vivakr
      POSTGRES_DB: vivakr
      TZ: 'Asia/Seoul'
    ports:
      - 59073:5432
    volumes:
      - ~/Docker/Postgres/Data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
